### ISSUE TITLE
check change passwd tac-ng

### ISSUE THREAD

**Issue by tsurkan4ik** [MarcJHuber/event-driven-servers#10]
Hi, Marc.
I've just figured out that your perl script hasn't checked the password complexity (I'm talking about the shadow backend). 

`curkanu.d@MacBook-Pro ~ % ssh test_box`
`Welcome`
`Password: "safely and long passwd"`
`Please change your password.`
`New password: "1"`
`Retype new password: "1"`
`Password change was successful.`

Could you please fix it? 

Regards,
D A

**Comment by MarcJHuber** [comment]
Hi,

mavis_tacplus_shadow.pl will perform a simple complexity check if the environment variable FLAG_PWPOLICY is set. 

This doesn't work for you even with "setenv FLAG_PWPOLICY = 1" in the module configuration?

Cheers,

Marc

**Comment by tsurkan4ik** [comment]
Hi again, 

Sorry, I missed this flag, now the script is checking the password complexity. 
Is it possible to force this script to check the matches with the previous password?
I was able to change the password to the previous one. 


Regards,
D A

**Comment by MarcJHuber** [comment]
Hi,

nice catch. I'll push a commit to check for password similarity (as a user I'd pretty much hate that).

Cheers,

Marc
