### ISSUE TITLE
Alternativ password If LDAP is temporary not available

### ISSUE THREAD

**Issue by DS819src** [MarcJHuber/event-driven-servers#103]
Hi,

is there a method, to gain access from same account if LDAP temporary unavailable with a secondary password, for example:

user admin01 {
           password login = mavis <-- provided from LDAP
           password login = crypt "$5$g.jtkC$JV...." <-- as second password method, only if the LDAP not available
           member = readwrite
}

Thanks in advance.

Best regards,

Daniel.

**Comment by MarcJHuber** [comment]
Hi Daniel,

basic support for that isn't hard to implement. Could you try [diff-password-fallback.txt](https://github.com/user-attachments/files/16470709/diff-password-fallback.txt) with "password login fallback = crypt ..."?

Cheers,

Marc

**Comment by DS819src** [comment]
Hi Marc,

thank you, I'll try to insert the diff and recompile it.

Cheers,

Daniel.

**Comment by DS819src** [comment]
Hi Marc,

thank you, it works. Will you push it into master branch?

Cheers,

Daniel.

**Comment by MarcJHuber** [comment]
Hi Daniel,

thanks for testing. Yes, I'll push this, just need some time to update the documentation, too.

Cheers,

Marc

**Comment by sanjmonkey** [comment]
Hi @MarcJHuber 

This appears to have broken the fallback-only functionality.  Now users with fallback-only always fail authentication.  Fallback-only does still work in previous commit, 28ef6c467ef7291c20eed6a22af0ecc86974c507

**Comment by MarcJHuber** [comment]
Hi Sandy,

this is hopefully fixed now, thanks!

Cheers,

Marc

**Comment by sanjmonkey** [comment]
That’s fixed it, thanks Marc!

**Comment by DS819src** [comment]
Hi Marc, 
just short reply from my site, it still works on my environment too.
Regards,
Daniel.
