### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by naciohr** [MarcJHuber/event-driven-servers#108]
Hello Marc,

I've built the current libraries for tac_plus-ng and the server is not responding as expected. It looks as if it's refusing connections and reparsing the configuration file at every connection attempt according to the debug logs.

I'm testing with [tacacs plus python client](https://tacacs-plus.readthedocs.io/en/latest/readme.html) and tactrace.pl and they are not able to connect to the server.

```bash
tactrace.pl --conf tac_plus-ng-test.cfg --key 0000 --realm <x> --user <x> --pass <x> --nad <x> --mode authc

The server process prematurely closed the connection.
```
Also, when I try to open a connection, the server is closing it.

```bash
telnet localhost 49
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

I've got the server dockerised and it's not working with the current libraries. However, if I take a previous docker image built on 8-aug, it works correctly with the same compose configuration file.

May you have a look, please?

Thanks and regards,

**Comment by MarcJHuber** [comment]
Hi,

thanks for reporting -- does 7d112c1d1d668228e8847565c493f5176b219762 fix this issue?

Thanks,

Marc

**Comment by naciohr** [comment]
Hello Marc,

Yes it does!

Thank you very much.

**Comment by MarcJHuber** [comment]
Thanks :-)
