### ISSUE TITLE
IOS switches problem

### ISSUE THREAD

**Issue by Idomaza** [MarcJHuber/event-driven-servers#110]
hi Marc,

I have an issue with my tacacs authentication to ios switches. I tried to get some help in your google group. You accused me for being an AI, and told me to opened an issue via github.

You said that there is a lack of debug output, the problem is that I don't know how to view those output messages. Moreover, the configuration file that i sent may have some syntax errors, this is because the organization I'm working in is air-gapped, therefore I had to manually copy my configuration while trying to share as little data as I can.

sorry for the misunderstanding, it will be great if you can unban me from the google group, and we can continue the chat from here.

Thanks

**Comment by MarcJHuber** [comment]
Hi,

thanks for explaining. Posting is possible again.

Sorry for being so paranoid.

Cheers,

Marc
