### ISSUE TITLE
Added SHA512 password

### ISSUE THREAD

**Issue by aztec102** [MarcJHuber/event-driven-servers#111]
Hello!
At the moment there is support for sha512crypt. Is it possible to add support for pure sha512?
Thank you in advance for your attention.
Example SHA512crypt
`$6$52450745$k5ka2p8bFuSmoVT1tzOyyuaREkkKBcCNqoDKzYiJL9RaE8yMnPgh2XzzF0NDrUhgrcLwg78xs1w5pJiypEdFX/`
Example SHA512 Hash
`82a9dda829eb7f8ffe9fbe49e45d47d2dad9664fbb7adf72492e3c81ebd3e29134d9bc12212bf83c6840f10e8246b9db54a4859b7ccd0123d86e5872c1e5082f`

**Comment by MarcJHuber** [comment]
Hi,

no, that's not an option. An unsalted SHA512 hash is unsuited for storing passwords as it greatly simplifies rainbow table attacks and just lacks any work factor that would make password guessing more expensive.

Cheers,

Marc
