### ISSUE TITLE
No connections available

### ISSUE THREAD

**Issue by naciohr** [MarcJHuber/event-driven-servers#112]
Hello Marc,

I have a doubt about how the service handles the idle connections. I found this situation where there are no connections available but the server is not spawning new instances.
![imaxe](https://github.com/user-attachments/assets/a57a7504-fa8e-4ee4-9eb0-6d6c78a918c4)

This is running inside a docker with the following spawnd settings.
```
id = spawnd {
	background = no
	listen { <3 ports and realms>}
	spawn {
		instances min = 2
		instances max = 8
	}
}
```

The consequence of the previous was no users could connect to TACACS. However, users could connect after reloading the service and the connection counter reset.
![imaxe](https://github.com/user-attachments/assets/0f3f5170-7f24-420d-b255-c0aa8304f768)

I would like to know if this behaviour is expected, as new connections are queued by default. I think it has to do with idle connections somehow, but I would expect all of those to show up there so I'd see 8 instances fully booked.

In the line of this, I would like to confirm whether _overload = close_ closes the oldest connections.

Thanks and regards,

**Comment by MarcJHuber** [comment]
Hi,

thanks for reporting. I'm not sure what's causing this, as the sum of the worker process connections should always be in sync with what the master process counts. I've only had limited time for testing today and have seen no issues, but I'll have a closer look during the next days (there's a public holiday ahead).

Regarding "overload = close": No, this will just immediately close the latest (current) connection as it can't be processed due to resource shortages.

Cheers,

Marc

**Comment by MarcJHuber** [comment]
Hi,

are you using the DNS reverse-lookup feature? If yes, then 8d52e89059b3211a862fb17b292c716cd12c9169 might fix the issue.

Thanks,

Marc

**Comment by naciohr** [comment]
Hello,

No, I'm afraid I don't use that feature.

BR,

**Comment by MarcJHuber** [comment]
Hi,

c9a46a6ca68580d8f5b0229189ad2843054bb87b likely fixes the issue you're seeing.

Thanks,

Marc

**Comment by naciohr** [comment]
Hello,

Many thanks for the patch. I will apply it and watch how the server behaves.

Regarding the idle connections, is there a way to prioritise new connections over old? From documentation I understand the options are to apply the retire limits, but according to the tests I did idle connections are keeping the spawnd instance active until they die.

Thanks and regards,

**Comment by MarcJHuber** [comment]
Hi,

I'll look at adding some last-recently-used evaluation to give new connections priority. This may (or may not) take a while.

Cheers,

Marc

**Comment by naciohr** [comment]
Hello,

Thank you very much. I think we can close this issue; I'll keep an eye on the updates of the repo.

Best regards,

**Comment by MarcJHuber** [comment]
Hi,

the latest push adds LRU support. Just add  "last-recently-used limit = <n>" to the tac_plus-ng section, with <n> a bit smaller than the "users max" from the spawnd section.

Cheers,

Marc
