### ISSUE TITLE
Not supported in rehl 9?

### ISSUE THREAD

**Issue by yash3339** [MarcJHuber/event-driven-servers#114]
I am installing tac plus in redhat 9 linux it seems it is not supported is it ? Or I am doing something wrong here

**Comment by MarcJHuber** [comment]
Hi,

the software should compile and run just fine on any Linux if the build dependencies are met. Are there any error messages?

Cheers,

Marc

**Comment by yash3339** [comment]
Hi there was no dependency error as such the  it say bad script and the file was rehl 5 , i am somthing like beginners to intermediate level guys can u please help me what type of dependency required , as per my knowledge all dependency are there in system , I will share you the errors will try once again

**Comment by MarcJHuber** [comment]
Hi,

you're trying to install an RPM? Then that's likely a package unrelated to this project and from another code base. I can't help with that.

To build a version of tac_plus-ng with low number of dependencies  you can easily run

```
git pull https://github.com/MarcJHuber/event-driven-servers.git
cd event-driven-servers
./configure --minimum tac_plus-ng
make
sudo make install
```

That's sufficient for most setups.

Cheers,

Marc

**Comment by yash3339** [comment]
![image](https://github.com/user-attachments/assets/e98ca8b6-8b7c-45cf-a9fd-b838e3b50e3f)
I installed it but there is no config file nor tac services created
check the snaps

**Comment by MarcJHuber** [comment]
Hi,

there's a demo config file installed in /usr/local/etc/mavis/tac_plus-ng.cfg, you'll need to customize that to suit your needs (or write a new one) and copy it to /usr/local/etc/tac_plus-ng.cfg. For starting the daemon as a service please have a look at tac_plus-ng/extra/tac_plus-ng.service.

Cheers,

Marc

**Comment by yash3339** [comment]
thanks mark I am able to install it , I have been using your tac_plus  version , I am trying to move that config in new tac_plus-ng , but it seems like it has different syntax for group and other , I am taking help from ur available doc , thank you so much for ur amazing code.
