### ISSUE TITLE
Ldapmavis-mt - nested groups 0 - reduce LDAP lookups

### ISSUE THREAD

**Issue by sanjmonkey** [MarcJHuber/event-driven-servers#122]
Hi Marc!

I’m trying to reduce the number of LDAP requests made, for a user authentication.  I’ve been looking at the current behaviour and notice that the initial default LDAP searchRequest is a wholeSubtree request for a user, for the attribute memberOf.  The LDAP server responds with all these group CN attributes.  Assuming I don’t want to look any further (no nested groups), I’m not sure there is any value in continuing to iterate these groups to look for memberOf again.  Could we not jump straight to the user bindRequest?  I simulated this behaviour with setting LDAP_NESTED_GROUP_DEPTH=-1, which stops the iteration over groups and jumps straight to bindRequest, but the tac reply is always fail.

what do you think about an option to stop the group recursion?

cheers
Sandy

**Comment by MarcJHuber** [comment]
Hi Sandy,

thanks for reporting -- does 2160ed922552a68e26e7e29efecfcc843bfea917 fix that issue?

Thanks,

Marc

**Comment by sanjmonkey** [comment]
Hi Marc, 

Doesn’t appear to I’m afraid.  Now with `LDAP_NESTED_GROUP_DEPTH=-1` we recurse the groups

**Comment by MarcJHuber** [comment]
Hi Sandy,

ok, thanks. I believe 77e73c9289e2a82a3c84c0070e79295f25b4ffc8 fixes the issue, care to test?

Thanks,

Marc

**Comment by sanjmonkey** [comment]
That’s the one!  Amazing work, thank you Marc!

**Comment by MarcJHuber** [comment]
Hi Sandy,

thanks for testing and confirming!

Cheers,

Marc
