### ISSUE TITLE
tac_plus-ng: Problem understanding IP ACLs + Core

### ISSUE THREAD

**Issue by mattablaze** [MarcJHuber/event-driven-servers#123]
Hey Marc, I sent a laundry list of things that I need assistance with to your google groups (that I suppose didn't get approved/moderated), so perhaps this is the better way to reach you and I'll break them up into individual "issues" even though they are likely just help with understanding the config.

I'm having a difficult time understanding how IP ACLs work for NAS access.  In our specific use case, we have a set of network devices that we don't want one specific user group/profile to be able to access.

In past versions of tacacs, we used the config logic like:

```
acl = tech_ro {
   # Allow Access TO all devices other than edge
      deny = 10.3.0.5
      deny = 10.3.0.6
      deny = 10.5.0.2
      # etc... many more
      permit = .*
}
```

Then that ACL was tied into a user group.   

```
group = tech_ro {
  default service = deny
  login = PAM
  acl = tech_ro
  service = exec {
    priv-lvl = 15
  }
  cmd = enable {
    permit .*
  }
# etc...  
}
```

For tac_plus-ng, I'm not sure where to apply a similar ACL.  For one thing, I haven't really found a need for "groups".  We're using profiles which are then mapped to a similar named group (with no configuration) and then that is mapped to the user name. 

I think I'm missing how the ACL I described above would work here.  I had thought we would add them in the "device <IP address>" area, but I ran into a problem where I tried to be selective with that config and it caused a core dump if there was no IPv6 address defined.  I have that and can share it off-list, as it might contain sensitive info.  

i.e. under 'device', if an IPv4 address other than 0.0.0.0/0 is used without an IPv6 address being defined, program crashes with error: "sh: 1: printf: printf: I/O error" + core.
```
  device staging {
       # address = ::/0
       address = 10.4.0.0/24
       welcome banner = "Welcome\n"
       enable 15 = clear secret
       key = secretstuff
       welcome banner = "Welcome, you're coming from ${client.address}\n"   
   }
```

I can share a full sanitized config if that would be helpful.

**Comment by MarcJHuber** [comment]
Hi,

alas, Google Groups has a history of being unreliable.

You can easily limit device access by checking whether a session matches a host condition:

device all {
    device edge { address = 10.3.0.5,10.3.0.6,10.5.0.2 }
    key = demo
}

and

script {
    if (device == edge) deny
}

either as part of the profile or the rule set.

Yes, I'd be grateful for a minimized config that actually crashes the daemon. I've tried, but couldn't reproduce that.

Cheers,

Marc

**Comment by mattablaze** [comment]
Ok, I was able to reproduce the core with this config.  A lot of it has been removed, and only the bare minimum is there to reproduce the core and also keep it sanitized.  

In this example, commenting out the defaults and adding the "10.2.0.0/15" produces a core when a user tries to login to a switch.

    device staging {
        #address = ::/0
        #address = 10.0.0.0/8
        address = 10.2.0.0/15
        welcome banner = "Welcome\n"
  }

root@tacacs-stg2-0000:~# /usr/local/sbin/tac_plus-ng /etc/tac_plus_ng/tac_plus_ng.conf
sh: 1: printf: printf: I/O error
Aborted (core dumped)
root@tacacs-stg2-0000:~#

The "Archive.zip" contains the core and config file to generate it. 

[Archive.zip](https://github.com/user-attachments/files/17722310/Archive.zip)

**Comment by MarcJHuber** [comment]
Hi,

thanks for the details -- alas, the core file would require the suitable binaries to be available, so it's not of much use.

I still can't reproduce the issue, your config works fine for me. Please reconfigure with debugging enabled (./configure --debug tac_plus-ng), rebuild and reinstall (make & sudo make install), then run the program under gdb (or lldb) control:

lldb tac_plus-ng
run /path/to/config-file

If there's a SEGV then please run "bt", followed by a number of "up" commands. This might give some insight.

Thanks,

Marc
