### ISSUE TITLE
Cisco Nexus AAA problem

### ISSUE THREAD

**Issue by tsurkan4ik** [MarcJHuber/event-driven-servers#13]
Hi, Marc.
Previously, I used the old tacacs+. I just installed tacacs-ng by your recommendation and it works fine.
But I have a question:
When I logging in to Cisco Nexus, it is not possible to enter even a single command. 
<img width="834" alt="image" src="https://user-images.githubusercontent.com/63451474/196393936-0335f888-008b-4995-aa1e-73f431e87916.png">

the problem config profile tacacs-ng:
```
profile = NetAdm {
        script {
                if (service == shell) {
                        if (cmd == "") {
                            set priv-lvl = 15
                            permit
                        }
                }
                if (service == junos-exec) {
                        if (cmd == "") {
                                set local-user-name = admin
                                permit
                        }
                }
                if (service == fortigate) {
                        if (cmd == "") {
                                set memberof = remote_adm
                                set admin_prof = roaccess
                                permit
                        }
                }
        }
}
```

The old configuration of tacacs hasn't have such problems:
```
group = NetworkAdmins {
        service = shell {
            default command = permit
            set priv-lvl = 15
        }
        service = junos-exec {
            set local-user-name = admin
        }
        service = fortigate {
            set memberof = remote_adm
            set admin_prof = roaccess
        }
}
```

I've just tested the old configuration and in case when I remove "default command = permit", Cisco Nexus is not allow me to execute any command. 

Is there any way to add default command = permit to tacacs+ ng config?
If you wish I can provide the full configuration.
Thank you. 

D A

**Comment by MarcJHuber** [comment]
Hi,

the equivalent to "default command = permit" would be to always return "permit".

<pre>    if (service == shell) {
        if (cmd == "") 
            set priv-lvl = 15
        permit
    }</pre>

Cheers,

Marc

**Comment by tsurkan4ik** [comment]
Hi, Marc. 
It is worked! Thanks!

D A

**Comment by MarcJHuber** [comment]
Hi,

great, thanks :-)

Cheers,

Marc
