### ISSUE TITLE
Cisco device not taking local authentication and checking tacacs server

### ISSUE THREAD

**Issue by yash3339** [MarcJHuber/event-driven-servers#130]
hey marc ,

I am back with on more problem , 

So I have cisco ASA which authenticate to the tacacs server and it is also configure with local as second method .
But when I try to access the device with local cred the tacacs server sending deny (no such user exist) and the device not falling back to local method it says access denied.

Can u suggest what changes I can make on tacacs config so that the cisco use local method when we try to use the local cred.

**Comment by MarcJHuber** [comment]
Hi,

that's normal behavior. Fallback to local users will only occur if the configured AAA server (TACACS+, RADIUS) stops answering.

If you can't mirror your device-only accounts to TACACS+ then there's no sane workaround for that. The best chance could be to open a Cisco TAC feature request for changing the evaluation order (local users first, then remote AAA).

Cheers,

Marc

**Comment by yash3339** [comment]
Hi ,

I think I am left with this option only thanks for the info marc.
