### ISSUE TITLE
service=pap authn broken in 1b90719

### ISSUE THREAD

**Issue by sanjmonkey** [MarcJHuber/event-driven-servers#132]
Hi Marc,

1b90719deca899f43b030afad6c3401cb3ced396 breaks service=pap authentication (eg F5's).  Devices using service=shell are  fine.  

I've tried debugging this through starting with `-d`, but weirdly all I see is just the single line output
`7: <timestamp> 0/00000000: <nas_ip> connection request from <nas_ip> (realm: default)` and nothing else (on highest debug level).    Server does not reply with anything to the client.  Its like its not reaching any part of the authentication code at all :/ 

Last working commit is a7eb61c87ad1ea99fd0957d4b7c21dc841e8c282 

Sorry its not much to go on!

Best
Sandy

**Comment by MarcJHuber** [comment]
Hi Sandy,

that's interesting. RADIUS support shouldn't have any impact on TACACS+ functionality. PAP works for me, too, both with local and MAVIS users.

Did this issue occur with the latest commit And you certainly did run "make clean" before building?

Thanks,

Marc

**Comment by johannesflaschberger** [comment]
Hi Marc.

Same story with Avocent ACS8048 Terminal Servers:
```
service = raccess {
	set group_name = admin;
}
```
PAP is also not working for me.

Johannes

**Comment by MarcJHuber** [comment]
Hi Johannes,

I just tested PAP with tac_plus-ng and even tac_plus, and both work for me (albeit tac_plus-ng only recently, there was a brief regression introduced by last nights commits).

Please provide debug output and a minimal configuration for reproducing this issue locally.

Cheers,

Marc

**Comment by sanjmonkey** [comment]
Hi Marc,

Apologies for the shallow bug report I opened originally, I hadn't had time then to fully look at what was going on here, but now I have and can add a bit more colour to what I'm seeing.

I'm running with a config similar to this:

```
id = spawnd {
    listen { port 49 }
        spawn {
            instances min = 5
            instances max = 10
        }
        background = no
}

id = tac_plus_ng {
    debug = ALL

    mavis module = groups {
        groups filter = /^$/
    }

    mavis module = external-mt {
        exec = /application/tac-plus-ng/sbin/ldapmavis-mt
    }

    user backend = mavis
    login backend = mavis
    pap backend = mavis
    mavis cache timeout = 1800
    cache timeout = 1800


    ##########
    # DEVICES #
    ##########

    device f5-lab-device {
        address = 10.10.10.10
        tag = os.f5
        key = some_key
    }

    ##########
    # PROFILES #
    ##########

    profile networkadmin {
        enable 15 = login
        script {
            if (service == ppp && protocol == ip) {
                if (device.tag == "os.f5") {
                     set F5-LTM-User-Info-1 = adm
                     set F5-LTM-User-Role = 0
                     set F5-LTM-User-Partition = all
                 }
            }
        permit
        }
    }

    ruleset {
        rule some-rule {
            enabled = yes
            script {
                if (user == testuser) { profile = netadmin permit }
            }
        }
    }
}
```

I then capture tacacs traffic and try to login to my `f5-lab-device` at `10.10.10.10`.

In the pcap I see the authentication Q, and the authentication R as pass.  I then see the authorisation Q and then no response.  

In the tacacs debug output I see the authentication request and response pass, and there it stops.  It does not log anything for the authorisation packet that I see on the wire.

However, theres a twist, its not consistent.  This happens say 9 times out of 10, and then all of a sudden, the tacacs daemon will process the authorisation packet and do the right thing and send a response.  I've tried changing lots of the config to see if I can see what might trigger a change in this behaviour (ie, instances = 1, removing the cache, etc) and I cannot find a pattern, so I'm not sure it is config related at all.

As for the tacacs authorisation packet from the F5, it is largely unremarkable.  The request has:
* Authentication type: PAP
* Service: PPP
* Port: ssh
* Remaddr len: 0
* Args:
  * service=ppp
  * protocol=ip

One thing I also notice, is that this authorisation packet is a reassembly of 2 TCP segments (first always 12B, with PSH flag, second always 42B), though I don't think its related as the authentication Q is also a reassembly in the same way.  I dont know why the F5 does this, but it is at least valid from a TCP perspective.

All other devices, mostly doing shell login, are not affected....

Again, sorry for the cryptic nature of the initial message, hoping this has some more detail in what to look for / where to look

Thanks
Sandy

**Comment by MarcJHuber** [comment]
Hi Sandy,

bdd1ece5f5d4b34a92fc3e6009657183b705d626 should resolve this issue. I've never noticed that in my setup: All of my test systems send TACACS+ packets in full, but at least F5 and Checkpoint Gaia send header and data separately, and the new code couldn't cope with the latter.

Thanks,

Marc

**Comment by sanjmonkey** [comment]
Thats fixed it, great work Marc, thank you!
