### ISSUE TITLE
tactrace.pl fails - missing Data::Radius::Constants module 

### ISSUE THREAD

**Issue by naciohr** [MarcJHuber/event-driven-servers#133]
Dear Marc,

I've built the latest version of tac_plus-ng and I'm finding this issue when trying to run `tactrace.pl`:

```bash
Can't locate Data/Radius/Constants.pm in @INC (you may need to install the Data::Radius::Constants module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /usr/local/bin/tactrace.pl line 186.
```

The last version I've got running dates 11-nov. I've checked the commits thereafter and it looks to be related to [tac_plus-ng/perl/tactrace.pl line 172](https://github.com/MarcJHuber/event-driven-servers/commit/1b90719deca899f43b030afad6c3401cb3ced396#diff-96b74cfc4b753c803e707e3abd8cfa1c49fd58b3553adf7f53d966b526b2815fR172) (sorry, the link doesn't seem to be redirecting to the line).

I reviewed the documentation and it already states we need `Net::TacacsPlus::Packet` , but I was wondering if that RADIUS module must be installed too even if the service is not set up at all.

Thanks and regards,

**Comment by MarcJHuber** [comment]
Hi,

I guess putting the RADIUS specific stuff into a Perl eval { } block and changing "use" to "require" should work. Give me a couple of minutes, this should be easy to implement.

Cheers,

Marc

**Comment by naciohr** [comment]
Hi Marc,

I confirm it works correctly.

Thanks a lot for the quick fix.
