### ISSUE TITLE
nas conditions not matching in rulesets

### ISSUE THREAD

**Issue by naciohr** [MarcJHuber/event-driven-servers#134]
Dear Marc,

I would like to report a potential issue with the ruleset evaluation process happening in the latest version of the code. It looks as if the matching conditions are not being processed correctly in the rules.

E.g. with this simple configuration snippet:

```
net net_local {
	address = 127.0.0.1
}
ruleset {
	rule cicd_test {
		enabled = yes
		script {
			if (nas == net_local && user == test) {
				profile = test_user
				permit
			}
		}
	}
}
```

This yields the following logs when testing using `tactrace.pl`.

```
127.0.0.1 user lookup succeded
127.0.0.1 evaluating ACL cicd_test
127.0.0.1  line 13: [nas] net 'net_cicd_tier2' => false
127.0.0.1  line 13: [&&] => false
127.0.0.1 ACL cicd_test: no match
```

However, the expected output should be:

```
127.0.0.1 user lookup succeded
127.0.0.1 evaluating ACL cicd_test
127.0.0.1  line 13: [nas] net 'net_cicd_tier2' => true
127.0.0.1  cmp: 'test' <=> 'test' = 1
127.0.0.1  line 13: [user] = 'test' => true
```

This last snipped was taken using the code dated 11-nov. Also I have tried replaced the deprecated name **nas** by **device** but I'm getting the same results.

What I noticed is that the service is throwing unexpected messages when it starts as though it didn't complete the initialisation:

```
116: file=/tmp/tac_plus-ng/tac_plus-ng/authen.c line=1796 sym=[<end-of-file>] buf=''
116: file=/tmp/tac_plus-ng/tac_plus-ng/authen.c line=1797 sym=[<string>] buf='${PASSWORD_EXPIRED}
' => buf='${PASSWORD_EXPIRED}
'
116: file=/tmp/tac_plus-ng/tac_plus-ng/authen.c line=1797 sym=[<string>] buf='${PASSWORD_EXPIRED}
'
116: file=/tmp/tac_plus-ng/tac_plus-ng/authen.c line=1797 sym=[<end-of-file>] buf=''
116: file=/tmp/tac_plus-ng/tac_plus-ng/authen.c line=1798 sym=[<string>] buf='${PASSWORD_EXPIRES}
' => buf='${PASSWORD_EXPIRES}
'
116: file=/tmp/tac_plus-ng/tac_plus-ng/authen.c line=1798 sym=[<string>] buf='${PASSWORD_EXPIRES}
'
116: file=/tmp/tac_plus-ng/tac_plus-ng/authen.c line=1798 sym=[<end-of-file>] buf=''
116: file=/tmp/tac_plus-ng/tac_plus-ng/authen.c line=1798 sym=[<string>] buf='${DENIED_BY_ACL}' => buf='${DENIED_BY_ACL}'
116: file=/tmp/tac_plus-ng/tac_plus-ng/authen.c line=1798 sym=[<string>] buf='${DENIED_BY_ACL}'
116: file=/tmp/tac_plus-ng/tac_plus-ng/authen.c line=1798 sym=[<end-of-file>] buf=''
```

Do you know why this could be happening?

Thanks and regards,

**Comment by MarcJHuber** [comment]
Hi,

thanks, I've pushed 7b112b52870b0565050323c42f5973a540075eb9, could you please check whether that fixes the issue?

Thanks,

Marc

**Comment by naciohr** [comment]
Hi Marc,

I tested the service and it's working again as it should.

Many thanks for your quick response.

BR,

**Comment by MarcJHuber** [comment]
Hi,

thanks, I'll then close this issue.

Cheers,

Marc
