### ISSUE TITLE
Hashed TACACS+ key

### ISSUE THREAD

**Issue by Lundmatt** [MarcJHuber/event-driven-servers#136]
Would it be possible to add the possibility to hash the TACACS+ key in the configuration file?

Would it make sense to add this possibility like it is for the passwords in the user definition in the configuration file?

Thanks

**Comment by MarcJHuber** [comment]
Hi,

no, both the server and the device need the key in plain text (for MD5 hash calculations), so this is not an option.

Cheers,

Marc
