### ISSUE TITLE
Not able to use logging in tacacs-ng

### ISSUE THREAD

**Issue by thegoggel** [MarcJHuber/event-driven-servers#15]
Hi

When adding:
    log authzlog { destination = /var/log/tac_plus/authz/%Y/%m/%d.log }
    log authclog { destination = /var/log/tac_plus/authc/%Y/%m/%d.log }
    log acctlog  { destination = /var/log/tac_plus/acct/%Y/%m/%d.log }
    accounting log = acctlog
    authentication log = authclog
    authorization log log = authzlog

to the config I get the following error message:
Invalid configuration file
7: /etc/tac_plus/tac_plus.cfg:16: Expected '=', but got 'log'
7: Detected fatal configuration error. Exiting.

**Comment by MarcJHuber** [comment]
Hi,

well, that's expected.

<pre>authorization log log = authzlog</pre>

comes with one "log" too much.

Cheers,

Marc

**Comment by MarcJHuber** [comment]
Hi,

is it safe to close this issue?

Thanks,

Marc

**Comment by MarcJHuber** [comment]
Closed.

**Comment by thegoggel** [comment]
Sorry for the late reply. But it works, a little bit embarrassed that I didn't see the double log entry.

Thanks
