### ISSUE TITLE
Tacacs-ng h3c issue 

### ISSUE THREAD

**Issue by tsurkan4ik** [MarcJHuber/event-driven-servers#17]
Hi, Marc!
Could you please help me with the process of password changing on h3c.
As you can see tacacs-ng returns very strange replies to NAS in case of using h3c:
 

<img width="559" alt="image" src="https://user-images.githubusercontent.com/63451474/198332367-6fa5f785-2f0c-4200-b3e8-9cbe52e9cfe7.png">

I've attached the log file from tacacs-ng server: 
[issue tacacs-ng debug.txt](https://github.com/MarcJHuber/event-driven-servers/files/9880871/issue.tacacs-ng.debug.txt)

Regards 
D A

**Comment by MarcJHuber** [comment]
Hi,

the H3C code returns the "Permission denied, please try again." message. Please file a case with H3C, there's simply no way to work around that on the tac_plus side..

Cheers,

Marc
