### ISSUE TITLE
tac_plus or tac_plus-ng support dynamic keys

### ISSUE THREAD

**Issue by cryol** [MarcJHuber/event-driven-servers#18]
Hello.

I have a need to use unique keys for each individual host, at the moment I have to use freeradius with the dynamic-clients module (the keys are stored in the mysql database or in redis, and are compared relative to ip during authorization).
I would like a similar functionality in tac _plus, since the ability to share privileges is more convenient than in freeradius.
It is possible to consider a financial reward for this functionality.

p.s. sorry for bad english.

Best regards, Cryol.

**Comment by MarcJHuber** [comment]
Hi Cryol,

alas, there's no trivial way to add DB support. I'd work around that by generating one or more configuration snippets based on the DB and include those into the daemon configuration. The daemon can easily cope with host specific keys, and if you don't change keys too often I'd consider that the occasional re-configuration, followed by a daemon restart, should be easy.

An integration of database support would result in a major redesign, and that's out of scope right now.

Cheers,

Marc
