### ISSUE TITLE
Tacacs-ng FortiGate issue

### ISSUE THREAD

**Issue by tsurkan4ik** [MarcJHuber/event-driven-servers#23]
Hi, Marc!
It's me again. 
Could you please help me with the process of password changing on FortiGate.
As you can see tacacs-ng is not returning replies:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/63451474/202414433-dfce3930-a193-4b12-ac3f-41e518b77a66.png">

I've attached the 2in1 config & log file from tacacs-ng server:
[issue tacacs-ng debug FG.txt](https://github.com/MarcJHuber/event-driven-servers/files/10030138/issue.tacacs-ng.debug.FG.txt)

Regards
D A

**Comment by MarcJHuber** [comment]
Hi,

alas, that's a PAP login:

```387048: 09:40:38.144 0/a682aac9: 10.99.255.1 action=login (1)
387048: 09:40:38.144 0/a682aac9: 10.99.255.1 authen_type=pap (2)
387048: 09:40:38.144 0/a682aac9: 10.99.255.1 service=login (1)
```

and RFC8907 states that

   _The entire exchange MUST consist of a single START packet and a
   single REPLY._ 

which forbids a multi-sequence exchange to ask for a new password.

I think it should be ok to at least pass on the "please change your password" message, but I'll have to verify this first.

Cheers,

Marc
