### ISSUE TITLE
configure tac_plus missing 

### ISSUE THREAD

**Issue by serhdan** [MarcJHuber/event-driven-servers#26]
Hello,
I get the following message when i configure with tac_plus option:
Development files were not found for: LIB-ARES, LIB-CURL, LIB-FREERADIUS, LIB-LWRES, LIB-PAM, LIB-PCRE2, LIB-RADCLI, LIB-SCTP, LIB-SSL, LIB-SSL_CRYPTO, LIB-TLS, LIB-ZLIB
Development files were found for: LIB-CRYPT, LIB-PCRE

My dist is Ubuntu 20.04
Linux host 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by MarcJHuber** [comment]
Hi,

that just indicates that the corresponding development environment isn't installed (e.g. libpam0g-dev, libc-ares-dev, ...). That's not actually an error, it just shows that some of the optional features aren't available on your system, due to missing development headers and libraries.

Cheers,

Marc

**Comment by serhdan** [comment]
Hello Marc, So there is no dependency which is missing?
Because I also get an error during the make:
# make
make: *** No rule to make target '.git/index', needed by 'misc/version.h'.  Stop.

**Comment by serhdan** [comment]
and make install error also:
make[1]: *** [GNUmakefile:24: install] Error 2
make: *** [GNUmakefile:34: install] Error 1

**Comment by MarcJHuber** [comment]
Hi,

that "no rule to make target '.git/index'" error is unusual as it would indicate that .git/index doesn't exist. Does it?

Cheers,

Marc

**Comment by serhdan** [comment]
I cloned the repository and uploaded to my server.
Errors are the same:
# make
make: *** No rule to make target '.git/index', needed by 'misc/version.h'.  Stop.

make install:
make[1]: Entering directory '/home/user/event-driven-servers-master/mavis'
make[2]: Entering directory '/home/user/event-driven-servers-master/mavis/perl'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/user/event-driven-servers-master/mavis/perl'
make[2]: Entering directory '/home/user/event-driven-servers-master/mavis'
make[2]: *** /home/user/event-driven-servers-master/build/linux-5.4.0-122-generic-x86_64/mavis: No such file or directory.  Stop.
make[2]: Leaving directory '/home/user/event-driven-servers-master/mavis'
make[1]: *** [GNUmakefile:24: install] Error 2
make[1]: Leaving directory '/home/user/event-driven-servers-master/mavis'
make: *** [GNUmakefile:34: install] Error 1

**Comment by MarcJHuber** [comment]
Hi,

please double-check that you've uploaded .git/index to your server, too.

Cheers,

Marc

**Comment by serhdan** [comment]
I am looking at the github and there is no .git folder
![event-driven-servers](https://user-images.githubusercontent.com/48884739/203247462-693e9a94-4b8f-47ea-ab02-44236568fa67.PNG)

**Comment by MarcJHuber** [comment]
Hi,

the ".git" directory is generated by the "git" command itself. You're not using that one for cloning but something different? That's currently not a sanctioned work-flow.

Give me a couple of minutes, I'll check out whether a missing .git directory can be worked-around by the "configure" script.

I'm pretty sure right now that any resulting builds will lack the "git rev-parse HEAD" hash version number and will be unsupported due to this.

Cheers,

Marc

**Comment by serhdan** [comment]
Thank you for the clarification,  I will also try to pull it via git command directly from my linux server.

**Comment by serhdan** [comment]
Hello again, that part is solved, thank you very much.
Another problem appears when I run "make":
event-driven-servers-master/misc/io_dns_revmap.c:17:10: fatal error: 'ares_nameser.h' file not found
#include <ares_nameser.h>

I have installed already libc-ares-dev and libc-ares2 , i can even see it when i run "./configure":
Development files were found for: LIB-ARES, LIB-CRYPT, LIB-PAM, LIB-PCRE2, LIB-SSL, LIB-SSL_CRYPTO, LIB-ZLIB

this my content of /usr/include:
/usr/include/ares_version.h
/usr/include/ares_rules.h
/usr/include/ares.h
/usr/include/ares_dns.h
/usr/include/ares_build.h

**Comment by MarcJHuber** [comment]
Hi,

thanks, according to https://c-ares.org/changelog.html the "ares_nameser.h" header was private until 1.18.0. I'll commit a fix shortly.

Cheers,

Marc

**Comment by serhdan** [comment]
Ignore my last message, I have solved it.
Ubuntu 20.04 comes with ares 1.15 , I have manually installed 1.18 and the compilation worked without errors.

Thank you very much for your great support.
