### ISSUE TITLE
undefined reference to symbol 'crypt@@XCRYPT_2.0' on Rocky Linux v8

### ISSUE THREAD

**Issue by pleedom** [MarcJHuber/event-driven-servers#27]
Hi Marc,

I'm experiencing the following error during the make step when compiling the current version on Rocky Linux v8. Would you be able to provide any guidance? Steps to reproduce below.

Error

clang -o tac_plus acct.o authen.o author.o buffer.o config.o dump.o main.o mavis.o packet.o report.o utils.o context.o -Wl,-rpath,$ORIGIN/../lib64 -L/root/rpmbuild/SOURCES/build/linux-4.18.0-425.3.1.el8.x86_64-x86_64/mavis -Wl,-rpath,/usr/local/lib64 -lmavis   -lcrypto -L/usr/lib -Wl,-rpath,/usr/lib -lpcre2-8
/usr/bin/ld: authen.o: undefined reference to symbol 'crypt@@XCRYPT_2.0'
//../lib64/libcrypt.so.1: error adding symbols: DSO missing from command line
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/root/rpmbuild/SOURCES/tac_plus/Makefile.obj:25: tac_plus] Error 1
make[2]: Leaving directory '/root/rpmbuild/SOURCES/build/linux-4.18.0-425.3.1.el8.x86_64-x86_64/tac_plus'
make[1]: *** [GNUmakefile:24: build] Error 2
make[1]: Leaving directory '/root/rpmbuild/SOURCES/tac_plus'
make: *** [GNUmakefile:31: dirs] Error 1

Observation

If I manually run the clang step with an extra "-lcrypt" it "appears" to work.

cd /root/rpmbuild/SOURCES/build/linux-4.18.0-425.3.1.el8.x86_64-x86_64/tac_plus
clang -o tac_plus acct.o authen.o author.o buffer.o config.o dump.o main.o mavis.o packet.o report.o utils.o context.o -Wl,-rpath,$ORIGIN/../lib64 -L/root/rpmbuild/SOURCES/build/linux-4.18.0-425.3.1.el8.x86_64-x86_64/mavis -Wl,-rpath,/usr/local/lib64 -lmavis -lcrypt  -lcrypto -L/usr/lib -Wl,-rpath,/usr/lib -lpcre2-8

Steps to Reproduce

Base Install of Rocky Linux v8

systemctl --now disable firewalld

# Update to current
dnf -y update

## Install EPEL Repositories
dnf -y install epel-release

# Install Dependencies (to compile tac_plus-ng from source and package into RPM)
dnf -y install \
 c-ares-devel.x86_64 \
 clang.x86_64 \
 freeradius-client-devel.x86_64 \
 gcc.x86_64 \
 git.x86_64 \
 keyutils-libs-devel.x86_64 \
 krb5-devel.x86_64 \
 libcom_err-devel.x86_64 \
 libcurl-devel.x86_64 \
 libkadm5.x86_64 \
 libretls-devel.x86_64 \
 libselinux-devel.x86_64 \
 libsepol-devel.x86_64 \
 libverto-devel.x86_64 \
 libxcrypt-devel.x86_64 \
 lksctp-tools-devel.x86_64 \
 make.x86_64 \
 openssl-devel.x86_64 \
 openssl3.x86_64 \
 openssl3-devel.x86_64 \
 openssl3-libs.x86_64 \
 pam-devel.x86_64 \
 pcre.x86_64 \
 pcre2-devel.x86_64 \
 pcre2-utf16.x86_64 \
 pcre2-utf32.x86_64 \
 perl.x86_64 \
 perl-Net-SSLeay.x86_64 \
 radcli-devel.x86_64 \
 rng-tools.x86_64 \
 rpmdevtools.noarch \
 rpmlint.noarch \
 rpm-build.x86_64 \
 rsyslog.x86_64 \
 tree.x86_64 \
 zlib-devel.x86_64

## Remove Previous Build
rm -rf ~/rpmbuild/

## Create RPM tree
rpmdev-setuptree

## Display RPM Build Tree
tree ~/rpmbuild

## Environment Variables (derived from https://github.com/MarcJHuber/event-driven-servers/blob/master/Makefile.inc)
current=`date +"%Y_%m_%d"`
TR=/usr/bin/tr
OSs=$(uname -s | env -i $TR "[:upper:]/ " "[:lower:]--")
OSr=$(uname -r | sed "s/(.*)//" | env -i $TR "[:upper:]/ " "[:lower:]--")
OSm=$(uname -m | env -i $TR "[:upper:]/ " "[:lower:]--")
OS=$OSs-$OSr-$OSm

## Disable Level 1 RPATH Errors
export QA_RPATHS=0x0001
# unset QA_RPATHS

## Typically run within an RPM spec file but manually performed for this issue.
cd ~/rpmbuild/
rm -rf ~/rpmbuild/SOURCES/
mkdir -p ~/rpmbuild/SOURCES/
cd ~/rpmbuild/SOURCES/
git clone https://github.com/MarcJHuber/event-driven-servers/ .

## Configure and make
CFLAGS= ./configure \
 --with-pam \
 --with-pcre \
 --with-pcre2 \
 --without-ares

make

**Comment by MarcJHuber** [comment]
Hi,

thanks, could you please git pull and check whether the configure script now recognizes libcrypt on your system?

Thanks,

Marc

**Comment by pleedom** [comment]
Hi Marc,

Tried the latest version and still get the same error.

We're found a workaround, but are not sure if it's elegant enough for primetime.

On Rocky Linux the package is known as "libcrypt"

[root@rocky1 SOURCES]# pkg-config --list-all | egrep -i crypt
libcrypt                       libxcrypt - Extended crypt library for DES, MD5, Blowfish and others
libxcrypt                      libxcrypt - Extended crypt library for DES, MD5, Blowfish and others
hogweed                        Hogweed - Nettle low-level cryptographic library (public-key algorithms)
nettle                         Nettle - Nettle low-level cryptographic library (symmetric algorithms)
libcrypto                      OpenSSL-libcrypto - OpenSSL cryptography library
libssl                         OpenSSL-libssl - Secure Sockets Layer and cryptography libraries
openssl                        OpenSSL - Secure Sockets Layer and cryptography libraries and tools
libcrypto3                     OpenSSL-libcrypto - OpenSSL cryptography library
libssl3                        OpenSSL-libssl - Secure Sockets Layer and cryptography libraries
openssl3                       OpenSSL - Secure Sockets Layer and cryptography libraries and tools
[root@rocky1 SOURCES]# 

but configure appears to look for "crypt"

check_for("CRYPT", "crypt", "crypt.h", "crypt", undef);

we added the following line beforehand

check_for("CRYPT", "libcrypt", "crypt.h", "crypt", undef);

the error has gone away :)

Kind regards Phil

**Comment by MarcJHuber** [comment]
Hi Phil,

thanks, the latest commit (153e906be3714a9c71a369dae26534bce1d17a18) should fix that issue, reliably.

Thanks,

Marc

**Comment by pleedom** [comment]
Hi Marc,

First pass looking good, I'll do some more testing tomorrow but I think this is ready to close.

Thank you

**Comment by MarcJHuber** [comment]
Hi Phil,

great, thanks!

It always surprises me how Linux distributions differ in library locations. The current code should cover that now, but we'll see.

Thanks again,

Marc

**Comment by pleedom** [comment]
Add a sprinkling of Windows, MacOS and Solaris and you’ve got a recipe for pain. Top job!

Regards Phil
