### ISSUE TITLE
OSLEVEL Detection Issues in Makefile.inc

### ISSUE THREAD

**Issue by strikerx22** [MarcJHuber/event-driven-servers#28]
I'm attempting to correct the following line of code; thus far, I can only confirm that this affects the following Linux platforms: CentOS, Ubuntu, Alpine. 

In Makefile.inc
```
OSLEVEL        := $(shell printf "0x%.2x%.2x%.4x" `echo $(OSr) | env -i $(TR) -c "[:digit:]" "[ *]"` 0 0 0 | cut -c-10)
```
I'm attempting to reverse engineer the desired outputs, I cannot determine what the complementary pattern is for the middle "tr -c" section is supposed to be. 

This currently causes "invalid number" errors like these below because the 'printf' command is expecting a number, not a string. At this time, the OSLEVEL function essentially strips the alpha characters and replaces them with ']'.  Based on the '[ *]' set in the translate command, I assumed that the intent was to replace the alpha chars with either a space or asterisk, but both of these would still result in strings and cause the same errors.

Errors:
```
sh: invalid number '3]10]0]1160]66]1]]]7]]86]64]'
sh: invalid number ''
sh: invalid number ''
```

**Comment by MarcJHuber** [comment]
Closing this one, the relevant code is no longer part of the GIT.
