### ISSUE TITLE
"prompt" keyword not recognised in tac_plus-ng.cfg

### ISSUE THREAD

**Issue by pleedom** [MarcJHuber/event-driven-servers#29]
Hi Marc,

Thanks for yesterday's update, #153e906 compiles beautifully on Rocky 8 now.

Moving onto configuration I've run a problem with the prompt configurable, in that it get's rejected within the host block with tac-plus-ng. Advice welcomed!

### Error message

```
Nov 24 15:14:32 rocky1 tac_plus-ng[7822]: Error /etc/tac_plus-ng/tac_plus-ng.cfg:62: Expected 'host', 'parent', 'authentication', 'permit', 'bug', 'pap', 'address', 'key', 'motd', 'welcome', 'reject', 'enable', 'anonymous-enable', 'augmented-enable', 'single-connection', 'debug', 'connection', 'context', 'rewrite' or 'script', but got 'prompt
```

### Configuration (Sanitised)

```
[root@rocky1 log]# cat /etc/tac_plus-ng/tac_plus-ng.cfg 
id = spawnd {
    listen = { 
        address = {{ip_addr}}
        port = 49
    }

    spawn = {
        instances min = 1
        instances max = 10
    }

    # background = yes
}

id = tac_plus-ng {

    log acctlog  {
        destination = /var/log/tacplusng/acct/%Y/%m/%d.log
    }

    log authzlog {
        destination = /var/log/tacplusng/authz/%Y/%m/%d.log
    }

    log authnlog {
        destination = /var/log/tacplusng/authn/%Y/%m/%d.log
    }

    log connlog  {
        destination = /var/log/tacplusng/conn/%Y/%m/%d.log
    }

    accounting log = acctlog
    authentication log = authnlog
    authorization log = authzlog
    connection log = connlog

    mavis module = groups {
        groups filter = /^(tier3|tier2|tier1)$/ # these are defined below
        memberof filter = /^CN=tacacs_/ # use this as a prefix
    }

    mavis module = external {
        setenv LDAP_SERVER_TYPE = "microsoft"
        setenv LDAP_HOSTS = "ldaps://{{ip_addr}}:636"
        setenv LDAP_BASE = "dc=contoso,dc=com"
        setenv LDAP_FILTER = "(&(objectclass=user)(sAMAccountName=%s))"
        setenv LDAP_USER = "tacacs@contoso.com"
        setenv LDAP_PASSWD = "{{password}}"
        setenv TACACS_GROUP_PREFIX = "tacacs_"
        setenv UNLIMIT_AD_GROUP_MEMBERSHIP = 1
        #setenv REQUIRE_TACACS_GROUP_PREFIX = 1
        exec = /usr/local/lib/mavis/mavis_tacplus_ldap.pl
    }

    login backend = mavis
    user backend = mavis
    pap backend = mavis

    host corporate {
        address = 0/0
        key = {{key}}
        prompt = "Prompt\n"
        motd banner = "MOTD\n"
        welcome banner = "Welcome\n"
    }


    profile tier1 {
        script {
            if (service == junos-exec) {
                set local-user-name = remote
                set deny-commands = "clear.*|configure.*|file.*|load.*|monitor.*|mtrace.*|op.*|request.*|restart.*|scp.*|set.*|ssh.*|start.*|telnet.*|test.*"
            }
            permit
        }
    }

    profile tier2 {
        script {
            if (service == junos-exec) {
                set local-user-name = remote
                set deny-commands = "clear.*|configure.*|file.*|load.*|op.*|request.*|restart.*|scp.*|set.*|ssh.*|start.*|telnet.*|test.*"
            }
            permit
        }
    }

    profile tier3 {
        script {
            if (service == junos-exec) {
                set local-user-name = remote
            }
            permit
        }
    }

    group tier1
    group tier2
    group tier3

    ruleset {
        rule {
            script { 
                    if (memberof =~ /^CN=tacacs_tier3,/) { profile = tier3 permit }
                    if (memberof =~ /^CN=tacacs_tier2,/) { profile = tier2 permit }
                    if (memberof =~ /^CN=tacacs_tier1,/) { profile = tier1 permit }
            }
        }
    }
}
```

**Comment by MarcJHuber** [comment]
Hi Phil,

thanks, looks like a documentation error. "welcome message" instead of "prompt" should work, I've dropped the "prompt" keyword there.

Thanks,

Marc

**Comment by MarcJHuber** [comment]
Hi Phil,

sorry, "welcome banner", not "welcome message".

Thanks,

Marc

**Comment by pleedom** [comment]
Many thanks Marc

I think SecureCRT might have been part of the problem as it was not displaying the the welcome banner correctly. Are you aware of any known issues with truncation of welcome banner text? Also is it possible to serve a custom password prompt?

Kind regards Phil

**Comment by MarcJHuber** [comment]
Hi Phil,

whether the welcome banner is displayed or not largely depends on the implementation. It may work, or the router drops it, or the SSH client does so. I'm not a SecureCRT user myself, I think both putty and openssh work.

Custom prompts have been on my to-do list for quite some time. I'll have another look at that later.

Best regards,

Marc

**Comment by MarcJHuber** [comment]
Hi Phil

the answer to "custom prompts" did just changes to "yes". 

message PASSWORD = ...

Cheers,

Marc

**Comment by pleedom** [comment]
Hi Marc,

This is great news, and much appreciated. I'll test tomorrow when back in the office.

Regards Phil

**Comment by pleedom** [comment]
Hi Marc,

I'm not sure which configuration context to place the message keyword in, I tried this ....

```
    host corporate {
        address = 0/0
        key = {{ key }}
        message PASSWORD = "Password: "
    }
```

and got this .....

```
Nov 28 12:34:13 rocky1 tac_plus-ng[7646]: Error /etc/tac_plus-ng/tac_plus-ng.cfg:62: Expected 'host', 'parent', 'authentication', 'permit', 'bug', 'pap', 'address', 'key', 'motd', 'welcome', 'reject', 'enable', 'anonymous-enable', 'augmented-enable', 'single-connection', 'debug', 'connection', 'context', 'rewrite' or 'script', but got 'message'
```

kind regards Phil

**Comment by MarcJHuber** [comment]
Hi Phil,

I've actually implemented this at realm (or default) level, but moving the functionality to host level might indeed be an option. I'll have a look at that.

Thanks,

Marc

**Comment by MarcJHuber** [comment]
Hi again,

the "message ..." directives should now work in host context.

Cheers,

Marc

**Comment by pleedom** [comment]
Thanks once again Marc,

Will try it out tomorrow morning.

Regards Phil

**Comment by pleedom** [comment]
Hi Marc,

Thanks for the explanation about context, I've tried the following in both default realm and hosts contexts and this is confirmed working for Putty and Rocky Linux ssh clients.

```
message PASSWORD = "Password"
```

I have a question about intended behaviour of this feature which relates to a trailing ": " being added to the prompt, is this needed?

Regards Phil

**Comment by MarcJHuber** [comment]
Hi Phil,

I originally thought that adding the trailing characters would be a good idea. The latest commit drops that idea.

Cheers,

Marc

**Comment by pleedom** [comment]
Thanks Marc

That'll do nicely, consider this issue closed.

Regards Phil

**Comment by MarcJHuber** [comment]
Hi Phil,

great, I've been waiting for that, I don't like open issues ;-)

Thanks,

Marc
