### ISSUE TITLE
The password changing logic is broken

### ISSUE THREAD

**Issue by lst123** [MarcJHuber/event-driven-servers#30]
Hello Mark, 

My Tacacs version is:
`tac_plus-ng version cb3983dfac094e8e1aa39939c44ae2132cff1ee3/PCRE2`
Before I faced an issue, I'd changed **lastChange** attribute to 0. 
So the first time the server asked me to change the password. I canceled the dialogue and tried once again.
The second time I wasn't been asked to enter the new password. 
![OnPaste 20221214-151045](https://user-images.githubusercontent.com/40116783/207541148-8f3e6a16-b261-4037-b944-1a57a2202ca2.png)

Regards,
Yaroslav

**Comment by lst123** [comment]
Hello Mark, 
Now everything is working as expected. 
Thank you for your help.

Regards,
Yaroslav

**Comment by MarcJHuber** [comment]
Hi Yaroslav,

great, thanks a lot!

Cheers,

Marc
