### ISSUE TITLE
groups filter stops working after Oct 2 change

### ISSUE THREAD

**Issue by kartiksubbarao** [MarcJHuber/event-driven-servers#31]
I have a `groups filter` similar to the one described in the documentation:
```
mavis module = groups {
  resolve gids = yes
  groups filter = /^(guest|staff)$/
  script out = {
    # copy the already filtered UNIX group access list to TACMEMBER
    eval $GIDS =~ /^(.*)$/
    set $TACMEMBER = $1
  }
}
```

This filter is not being applied properly since the following change on Oct 2: https://github.com/MarcJHuber/event-driven-servers/commit/14b3391d0d0d539494707be42914be7719ac08f5. I get errors like the following which I did not get before:
`1367463: 19:17:11.457 0/00000000: - jsmith:1: Group 'labs-dev' not found`

The problem seems to be with the following two lines of code that were deleted in that change:

![image](https://user-images.githubusercontent.com/134209/208009062-86e58d87-ec7b-460a-a9b5-d94f1d265962.png)

The `good_name()` function (which calls `rxmatch()` with the actual filter) is no longer being called on the AV_A_GIDS field. That means that GIDS still has the full list of resolved groups, which gets copied to TACMEMBER.

This patch seems to later introduce filtering on AV_A_TACMEMBER, but I don't see how to benefit from that since GIDS is the attribute that contains the list of resolved groups. Please clarify if there is another way we should be setting up group filtering after the Oct 2 change, or whether the code needs to be updated to keep filtering working as documented.

**Comment by MarcJHuber** [comment]
Hi Kartik,

fixed, thanks a lot!

Cheers,

Marc

**Comment by kartiksubbarao** [comment]
Thanks Marc!
