### ISSUE TITLE
groups_getlist() implementation of getgrouplist() doesn't match the libc implementation with sssd enabled

### ISSUE THREAD

**Issue by kartiksubbarao** [MarcJHuber/event-driven-servers#32]
When sssd is enabled with default settings (`sss` is included for groups in /etc/nsswitch.conf and `enumerate` is set to `False` in /etc/sssd/sssd.conf), the libc implementation of `getgrouplist()` on Ubuntu 22.04 correctly returns all groups for a user. However, the mavis/groups.c implementation of this functionality in `groups_getlist()` does not. The reason is because it relies on `getgrent()` to iterate through all groups, which is presumably precluded by `enumerate=False`. Whereas the libc `getgrouplist()` function is able to return a user's groups without needing to enumerate all nonlocal groups.

Currently, I'm working around this by modifying misc/sysconf.h to unconditionally define these two symbols:

```
#define HAVE_GETGROUPLIST
#define GETGROUPLIST_ARG2_TYPE gid_t
```

It would be nice to be able to do this without modifying the code. One thought would be to change the `#if 0` line in misc/sysconf.h that unconditionally disables HAVE_GETGROUPLIST, to something like `#ifdef WITH_GETGROUPLIST`. And then in configure, allow people to specify `--with-getgrouplist` to define that symbol. I'd be happy to submit a pull request if you want, let me know what you think.

**Comment by MarcJHuber** [comment]
Hi Kartik,

thanks, I've just checked a couple of non-Linux systems, all support getgrouplist() (and only Apple still uses the older API with int instead of git_t). I'll commit a fix.

Thank you and best regards,

Marc

**Comment by kartiksubbarao** [comment]
Awesome, thanks Marc!
