### ISSUE TITLE
Local used variable won't be free until user is free-ed

### ISSUE THREAD

**Issue by mythjill** [MarcJHuber/event-driven-servers#34]
refer to 
https://github.com/MarcJHuber/event-driven-servers/blob/114cd580c63d54481bf9a2c947faaa3ee33652a0/tac_plus/config.c#L1716

hl is malloced in certain case, but point to nas_limit_dflt inside user object in other case. If it is malloced inside the function, better free it here, otherwise only be free-ed until user is free-ed.

**Comment by MarcJHuber** [comment]
Hi,

this is by design. The strings in hl are referenced in the radix tree structure, later on.

Cheers,

Marc
