### ISSUE TITLE
`pammavis` usage is wrong in the documentation and samples

### ISSUE THREAD

**Issue by gregoo** [MarcJHuber/event-driven-servers#4]
I've been trying to understand why I couldn't authenticate users against `pam` and ended up adding a bunch of `printf` to `pammavis.c`.
In the doc and samples, for some reason the first argument of `pammavis` is `pammavis` again, while it seems it only expects the option `-s <service>`.

That is the configuration bit from the documentation: https://www.pro-bono-publico.de/projects/tac_plus-ng.html#AEN2282
```plain
  mavis module = external {
    exec = /usr/local/sbin/pammavis pammavis -s sshd
  }
```

It turns out that if the first argument is `pammavis`, the tool will discard the rest of the arguments and silently set the `service` variable to its default value `mavis`. Obviously with targeting the wrong `pam` service, authentication does not work.

- Double `pammavis`, bogus credentials
```plain
/ # printf "4 gregory\
n8 password\n=\n" | /usr/local/sbin/pammavis pammavis -s sss_fromhost
4 gregory
8 password
authenticating gregory
pam_start res: 0, service: mavis
pam_authenticate res: 10
=16
```
Service is set to `mavis`, `pam_authenticate` returns `PAM_USER_UNKNOWN`

- Single `pammavis`, bogus credentials
```plain
/ # printf "4 gregory\
n8 password\n=\n" | /usr/local/sbin/pammavis -s sss_fromhost
service: sss_fromhost
4 gregory
8 password
authenticating gregory
pam_start res: 0, service: sss_fromhost
pam_authenticate res: 7
17 Authentication failure
6 NAK
=0
```
Service is set to `sss_fromhost`, `pam_authenticate` returns `PAM_USER_UNKNOWN`

- Single `pammavis`, valid credentials
```plain
/ # printf "4 gregory\
n8 <REDACTED>\n=\n" | /usr/local/sbin/pammavis -s sss_fromhost
service: sss_fromhost
4 gregory
8 <REDACTED>
authenticating gregory
pam_start res: 0, service: sss_fromhost
pam_authenticate res: 0
success
=16
```
Service is set to `sss_fromhost`, `pam_authenticate` returns `PAM_SUCCESS`

**Comment by MarcJHuber** [comment]
This works as designed. The first argument to "exec =" specifies the path, the others the arguments for execve(2), starting with argv[0].
