### ISSUE TITLE
Outdated tac_plus-ng documentation

### ISSUE THREAD

**Issue by Luth1ng** [MarcJHuber/event-driven-servers#43]
Hello Marc,

I realize that in the last versions of tac_plus-ng, the syntax of the configuration has changed drastically.
I have difficulty using the various configuration attributes without documentation.

Could I have missed a new version of the documentation?
Is it planned to be updated?

Cheers

**Comment by MarcJHuber** [comment]
Hi,

I don't remember any syntax changes, and I usually take care to retain backwards compatibility. Could you please submit a sample?

Cheers,

Marc

**Comment by Luth1ng** [comment]
It seems that mainly the Sample Configuration chapter is outdated.
I am using for reference the tac_plus-ng.pdf doc file where the date in the doc is set to March 12, 2023.

Some examples:

  - "Sample Configuration" chapter page 6 - defining users :
	The documentation is updated (page 34.) but this chapter says : 
		"password = clear demo"

  - "Banners and Messages" chapter page 26 :
  	The directive "failed authentication banner" in the table is not a valid syntax :
	 	Expected 'host', 'parent', 'authentication', 'permit', 'bug', 'pap', 'address', 'key', 'motd', 'welcome', 'reject', 'enable', 'anonymous-enable', 'augmented-enable', 'single-connection', 'debug', 'connection', 'context', 'rewrite' or 'script', but got 'failed'

  - "Users" chapter page 35
  	The directive "groups" is not working anymore : the documentation is updated but not the "Sample Configuration" chapter which contains "groups" directive (page 6.)

NB: Also, Regex cmd condition works only without the "/", but not sure if this deals with --with-pcre2 configure option?

**Comment by MarcJHuber** [comment]
Hi,

first, thanks for reading the documentation!

I've corrected the issues you've mentioned. There are quite likely a couple more, and I'll try to proofread the docs when time permits.

Yes, a regex enclosed in "/" is PCRE syntax. I think I'll drop support for both POSIX and PCRE1 later this year and make PCRE2 mandatory. 

Cheers,

Marc

**Comment by MarcJHuber** [comment]
Hi,

I think it's safe to close this issue. Is that fine for you?

Cheers,

Marc

**Comment by MarcJHuber** [comment]
No timely reply, so done.
