### ISSUE TITLE
tac_plus: Timeout for non-responding ldap-servers

### ISSUE THREAD

**Issue by mboehm21** [MarcJHuber/event-driven-servers#46]
We are using tac_plus with two defined ldap-servers:

```
        mavis module = external {
                setenv LDAP_SERVER_TYPE = "openldap"
                setenv LDAP_HOSTS = "ldap1 ldap2"
...
                exec = /usr/local/lib/mavis/mavis_tacplus_ldap.pl
        }
```

How can we configure the timeout for tac_plus to try the second server when the first one is unreachable? The default seems too long for the routers to wait.

Thanks a lot.

**Comment by MarcJHuber** [comment]
Hi,

``setenv LDAP_CONNECT_TIMEOUT = 1``

should work. Default is 5 seconds (which is arguably too large).

Cheers,

Marc
