### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by JokerYYW01** [MarcJHuber/event-driven-servers#47]
I updated my tac_plus to tac_plus_ng recently.  When I used the old conf file, I got misstake like this:
`        group =  g_en {
                default 
../etc/tac_plus-ng.cfg.bak:43: Expected 'group' or 'parent', but got 'default'
61389: ../etc/tac_plus-ng.cfg.bak:43: Expected 'group' or 'parent', but got 'default'
61389: Detected fatal configuration error. Exiting.`

i wanna how to convert configuration item below to new version
        group = g_nen {
                default service = permit
                enable = deny
        }

Thanks  for your help

**Comment by MarcJHuber** [comment]
Hi,

configurations between tac_plus and tac_plus-ng are fundamentally different, please have a look at tac_plus-ng/sample/tac_plus-ng.cfg for an example.
```
profile g_nen {
    enable = deny
    script { permit }
}

group g_nen

user demo { member = g_nen ... }

ruleset {
    rule g_nen {
        script {
            if (member == g_nen) {
                 profile = g_nen
                 permit
            }
        }
    }
}
```
might come close to your use case.

Cheers,

Marc

**Comment by MarcJHuber** [comment]
No response, so I'm closing this issue.
