### ISSUE TITLE
Compile error since commit 5ed6cbc66be00d3cf090dbae88650a0038d8b1c6  (tac_plus-ng: add dns name logging)

### ISSUE THREAD

**Issue by beranf** [MarcJHuber/event-driven-servers#48]
Command "make" terminates with an error (see the attachments for details) since pull the latest commit 5ed6cbc66be00d3cf090dbae88650a0038d8b1c6 
[bug_compile_configure.log](https://github.com/MarcJHuber/event-driven-servers/files/11624483/bug_compile_configure.log)
[bug_compile_make.log](https://github.com/MarcJHuber/event-driven-servers/files/11624484/bug_compile_make.log)

My linux OS:
[cat /etc/os-release]
NAME="AlmaLinux"
VERSION="9.1 (Lime Lynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.1 (Lime Lynx)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"

**Comment by MarcJHuber** [comment]
Hi Filip,

thanks! Did you compile that with the --debug option? Under normal circumstances, this should throw a warning only. I'll push a fix.

Cheers,

Marc

**Comment by beranf** [comment]
Hi Marc,
yes, I used compile with --debug option. I used compile with following options:
`./configure --debug mavis mavisd spawnd tac_plus-ng`

Filip

**Comment by beranf** [comment]
Hi Marc,
latest commit passes compiling sucessfully with --debug option.  Thank you!
Filip
