### ISSUE TITLE
authentication log configuration file issue

### ISSUE THREAD

**Issue by janmaris** [MarcJHuber/event-driven-servers#5]
Hi,

I don’t seem to be able to complete the config line item for the authentication log specification.

     18     log authzlog { destination = /var/log/tac_plus/authz/%Y/%m/%d.log }
     19     log authclog { destination = /var/log/tac_plus/authc/%Y/%m/%d.log }
     20     log acctlog  { destination = /var/log/tac_plus/acct/%Y/%m/%d.log }
     21
     22     authentication log = authclog
     23     accounting log = acctlog
     24     authorization log = authzlog

When I start the process, the parser gives the following error message:

./tac_plus-ng.conf:22: Expected '=', but got 'log'

Am I overlooking something or could this be a bug?
(I’ve compiled on Debian 11.)

Thanks.

Cheers,
Jan

**Comment by MarcJHuber** [comment]
Hi Jan,

it's a bug, thanks for reporting that issue! I've just pushed a fix.

Cheers,

Marc

**Comment by janmaris** [comment]
Hi Marc,

thank you very much for this quick fix!

Cheers,
Jan
