### ISSUE TITLE
tacplus-ng:   Regular expression matching is unsupported for 'nac'  since b5d4dada8a326f3e3a02690ad3cbd9fa67a0882b

### ISSUE THREAD

**Issue by beranf** [MarcJHuber/event-driven-servers#53]
Hi Marc,
since you have pushed commit 'b5d4dada8a326f3e3a02690ad3cbd9fa67a0882b' you have been denying regular expression matching for 'nac' variable.  Is it really intended/wanted restriction so? I suppose it is a bug.

Thank you in adnvaced.
Regards,
Filip

**Comment by MarcJHuber** [comment]
Hi Filip,

you're right, this wasn't well thought out. I'll push a fix.

Thanks,

Marc

**Comment by MarcJHuber** [comment]
Hi,

on second thought, I don't believe that comparing nac/nas (that's client or server IP address in ASCII) to a regex was ever a documented feature.

I'll have a closer look when time allows. Moving from "nas" to "host" and from "nac" to "client" looks like be viable option, too. That syntax is already moving to a state of too much complexity.

Cheers,

Marc

**Comment by beranf** [comment]
Hi Marc, 

in fact your documentation for **tacplus-ng** contains following railroads for TacCond (snippet from the page 31):
![tacplus-ng__TacCond__nac-nas-nac-name_nas-name](https://github.com/MarcJHuber/event-driven-servers/assets/32090064/383d3f26-bca8-40f0-af7c-fc34fea36c80)

Regards,
Filip

**Comment by MarcJHuber** [comment]
Hi Filip,

thanks ... I totally forgot about that. "nac" regex matching might be useful for non-IP remote addresses, but "nas" is guaranteed to be an IP address. Not sure why I've implemented that.

Cheers,

Marc

**Comment by beranf** [comment]
Hi Marc,

thank you, I think 'nac' regex matching can be very useful for example if you test if a client access from specific subnet(s) - this you will not be able to validate without regex. So current implementation is fine and correct I think. 
BTW, I confim, that your last commit (b5d4dada8a326f3e3a02690ad3cbd9fa67a0882b) fixes the issue ;-), Thank you

Regards,
Filip
