### ISSUE TITLE
Log file format config error

### ISSUE THREAD

**Issue by corrugatedcardboard** [MarcJHuber/event-driven-servers#63]
Dear MarcJHuber,

first of all, thank you for this software project and your dedication to it, it greatly helped me.

Sadly, it appears I have run into a small config problem.

According to the documentation (https://www.pro-bono-publico.de/projects/tac_plus-ng.html#AEN384, Chapter 4.2.3.1 Logging), I should be able to format the log output in the files like this:

`( authentication | authorization | accounting ) format = string`

So, I decided to incorporate this option in my config file like this:
`authentication format = "%Y-%m-%d %H:%M:%S %z\t${device.dnsname}\t${user}\t${port}\t${client.dnsname}\t${action} ${hint}\n"`

However, when I use this config command, and let the debugger (tac_plus-ng -P config.cfg) run over it, it throws out this error:

```
id = tac_plus-ng {

	#log authzlog { destination = /var/log/tac_plus/%Y/%m/%d.log }

    	#log authclog { destination = /var/log/tac_plus/%Y/%m/%d.log }

    	log taclog  { destination = /var/log/tac_plus/SERVERNAME/%Y%m%d.log }

    	accounting log = taclog

    	authentication log = taclog

    	authorization log = taclog
	
	authentication format 
config.cfg:34: Expected 'fallback' or 'log', but got 'format'
24122: config.cfg:34: Expected 'fallback' or 'log', but got 'format'
24122: Detected fatal configuration error. Exiting.
``` 

Did I use the command wrong? Or am I missing something?

**Comment by MarcJHuber** [comment]
Hi,

DNS resolution is handled using c-ares, so libc-ares-dev (or similiar, that's the Ubuntu package name) needs to be installed.

Please use the current GIT, I've pushed some fixes today.

Cheers,

Marc
