### ISSUE TITLE
Not using cached data for authorization with LDAP

### ISSUE THREAD

**Issue by naciohr** [MarcJHuber/event-driven-servers#69]
Hello Marc,

I'm having trouble with the LDAP authorization process. Authentication works correctly and information is retrieved from LDAP.

However, when processing the authorization, I noticed TACACS asks the LDAP module again for the user rather than using the cached information from the authentication.

I had the module built and running from beginning August and the process works: authentication retrieves the information from the LDAP and uses the cached data to process the authorization - no faults. However, I've built the module last week and that part is failing.

I see a lot of commits from the beginning of August until now, so I was wondering whether there's been a change in the way the cache works, or I must tell tacacs to cache that data specifically.

Thanks and regards,

**Comment by MarcJHuber** [comment]
Hi,

thanks a lot for reporting this, I accidentally discarded a few defaults and didn't notice. I'll push a fix.

Thanks,

Marc

**Comment by naciohr** [comment]
Hi Marc,

Just to let you know it's working now. Thank you very much.
