### ISSUE TITLE
tac_plus

### ISSUE THREAD

**Issue by lst123** [MarcJHuber/event-driven-servers#7]
Hello,
I think something wrong with the logic of password changing in case when I use shadow file as a backend. 
When I force user to change the password during the next login:

`test:$1$aINRlZ00$xqbEmgJNanAX.LhRiPVZZ/:1:1:0:99999:0:`
 Tacacs server is asking for password:

```
lst@lsts-MacBook-Pro ~ % ssh test@leaf3
(test@leaf3)
Hello user with ip: 192.168.11.110

Password:
(test@leaf3) Please change your password.
Old password:
Permission denied.
```

When I use the same password as it was before everything is fine, mavis_tacplus_shadow.pl is overwriting hash and lastChange in the users attributes in shadow file. 

If it possible to fix it or not?

**Comment by MarcJHuber** [comment]
Hi,

I'm unable to confirm this. Please provide more details. Password changes work just fine for me in the testing environment with

```
id = spawnd {
        listen = { port = 49 }
        spawn = {
                instances min = 1
                instances max = 1
        }
        background = yes
}

id = tac_plus {
        mavis module = external {
                setenv SHADOWFILE = "/home/ubuntu/PROJECTS-private/tac_plus-ng/sample/shadow"
                exec = /usr/local/lib/mavis/mavis_tacplus_shadow.pl
        }

        login backend = mavis chpass

        host = world {
                address = ::/0
                prompt = "Welcome\n"
                enable 15 = clear secret
                key = demo
        }

        group = admin {
                default service = permit
                service = shell {
                        default command = permit
                        default attribute = permit
                        set priv-lvl = 15
                }
        }


        user = marc {
                password login = mavis
                member = admin
        }
}
```

Cheers,

Marc

**Comment by lst123** [comment]
Hi Mark, 
I'm totally confused because I tried your config with tacacs-ng server and got several errors:
```
Oct  5 07:24:51 deb11-2 tac_plus-ng[36689]: startup (version a1b922b69908e66e3e48027c40a0b4597b064315)
Oct  5 07:24:51 deb11-2 tac_plus-ng[36689]: epoll event notification mechanism is being used
Oct  5 07:24:51 deb11-2 tac_plus-ng[36689]: bind to [::]:49 succeeded
Oct  5 07:24:51 deb11-2 tac_plus-ng[36690]: Error /usr/local/etc/tac_plus-ng.cfg:39: FATAL: No configuration for id 'tac_plus-ng' found.
```
When I changed id in tac_plus-ng.cfg from tac_plus to:
```
id = tac_plus-ng {
        mavis module = external {
                #setenv FLAG_PWPOLICY=y
                setenv SHADOWFILE = /usr/local/etc/shadow_tac
                exec = /usr/local/lib/mavis/mavis_tacplus_shadow.pl
        }
```
Server refused to start again:
```
Oct  5 07:25:23 deb11-2 tac_plus-ng[36710]: Error /usr/local/etc/tac_plus-ng.cfg:20: Expected 'host', 'parent', 'authentication', 'permit', 'bug', 'pap', 'address', 'key', 'motd', 'welcome', 'reject', 'enable', 'anonymous-enable', 'augmented-enable', 'single-connection', 'debug', 'connection', 'context', 'rewrite' or 'script', but got 'prompt'
Oct  5 07:25:23 deb11-2 tac_plus-ng[36709]: Child reported fatal configuration problem. Exiting.
Oct  5 07:25:23 deb11-2 tac_plus-ng[36710]: Error Detected fatal configuration error. Exiting.
Oct  5 07:25:23 deb11-2 systemd[1]: tac_plus.service: Main process exited, code=exited, status=78/CONFIG
Oct  5 07:25:23 deb11-2 systemd[1]: tac_plus.service: Failed with result 'exit-code'.
Oct  5 07:25:24 deb11-2 systemd[1]: tac_plus.service: Scheduled restart job, restart counter is at 5.
Oct  5 07:25:24 deb11-2 systemd[1]: Stopped TACACS+ Service.
Oct  5 07:25:24 deb11-2 systemd[1]: tac_plus.service: Start request repeated too quickly.
Oct  5 07:25:24 deb11-2 systemd[1]: tac_plus.service: Failed with result 'exit-code'.
Oct  5 07:25:24 deb11-2 systemd[1]: Failed to start TACACS+ Service.
```

So I've return back to the other tac_plus (not ng) installation. My full config is:
```
#!/usr/local/sbin/tac_plus

id = spawnd {
        listen = { port = 49 }
        spawn = {
                instances min = 1
                instances max = 20
        }
        background = no
}

id = tac_plus {
    debug = PACKET AUTHEN AUTHOR

    access log = /var/log/tacplus/access_%Y%m%d.log
    authorization log = /var/log/tacplus/authorization_%Y%m%d.log
    accounting log = /var/log/tacplus/accounting_%Y%m%d.log
    retire limit = 1000

    login backend = mavis chpass
    pap backend = mavis
    mavis module = external {
      setenv SHADOWFILE = /usr/local/etc/shadow_tac
      #setenv FLAG_PWPOLICY=y
      exec = /usr/local/lib/mavis/mavis_tacplus_shadow.pl
    }
    host = ANYv4 {
        welcome banner = "\nHello user with ip: %%c\n"
        failed authentication banner ="\nAre you the %%u?\n"
        address = 0.0.0.0/0
    }
    host = Dataline {
        address = 10.255.64.0/24
	    key = TESTDEVICE11
    }
    group = NetworkAdmins {
        default service = permit
        enable = permit
        service = shell {
            default command = permit
            default attribute = permit
            set priv-lvl = 15
        }
        service = junos-exec {
            set local-user-name = admin
        }
    }
    group = NetworkDCAdmins {
        member = NetworkAdmins
    }
    user = test2 {
        member = NetworkAdmins@10.0.0.0/8
    }
}
```
When I force user to change password I see this during the next login:
<img width="752" alt="Screenshot 2022-10-05 at 15 04 05" src="https://user-images.githubusercontent.com/40116783/194024783-98d977eb-3395-47b6-bf31-f1288d2c0717.png">

Shadow file before:
`test2:$1$aINRlZ00$xqbEmgJNanAX.LhRiPVQT/:0:0:99999:0:`
Shadow file after:
`test2:$1$65WfpIMf$9mwZvFbvrFiICkuukOs7d/:19270:0:99999:0:`

The installation is fresh. Just cloned from github and recompile it.
Tacacs server version is: 
`a1b922b69908e66e3e48027c40a0b4597b064315`

**Comment by MarcJHuber** [comment]
Hi,

ok, thanks, so the backend indicates that the password should be changed, I thought that the password change dialog would be triggered by an empty password.

I've just pushed sample shadow backend configurations for both tac_plus and tac_plus-ng and added a couple of other minor fixes. For tac_plus-ng (I didn't check with tac_plus), the output now looks like:

<pre>$ telnet 10.0.0.1
Trying 10.0.0.1...
Connected to 10.0.0.1.
Escape character is '^]'.

Welcome

Username: demo
Password:

Please change your password.

Old password:

New password:

Retype new password:
Password change was successful.


router#exit</pre>

Could you please git pull and check whether this is working for you, too?

Thanks,

Marc

**Comment by lst123** [comment]
Hello Mark again,
Thank you for the new build. 

I've just installed the new version of Tacacs server NG:
`a1b922b69908e66e3e48027c40a0b4597b064315`

And nothing seriously changed, I'm able to see the same behaviour:
Tacacs NG logs:
```
Oct  5 15:17:34 deb11-2 tac_plus-ng[40576]: - Version a1b922b69908e66e3e48027c40a0b4597b064315 initialized
Oct  5 15:17:34 deb11-2 tac_plus-ng[40576]: epoll event notification mechanism is being used
Oct  5 15:17:43 deb11-2 dhclient[428]: DHCPREQUEST for 192.168.0.172 on ens3 to 192.168.0.1 port 67
Oct  5 15:17:44 deb11-2 dhclient[341]: DHCPREQUEST for 192.168.0.172 on ens3 to 192.168.0.1 port 67
Oct  5 15:17:45 deb11-2 tac_plus-ng[40576]: 10.255.64.3 looking for user test2 in MAVIS backend
Oct  5 15:17:45 deb11-2 tac_plus-ng[40576]: 10.255.64.3 verdict for user test2 is ACK
Oct  5 15:17:45 deb11-2 tac_plus-ng[40576]: 10.255.64.3 shell login for 'test2' from 10.20.20.19 succeeded [Please change your password.] (profile=admins)
Oct  5 15:17:46 deb11-2 tac_plus-ng[40576]: 10.255.64.3 looking for user test2 in MAVIS backend
Oct  5 15:17:46 deb11-2 tac_plus-ng[40576]: 10.255.64.3 verdict for user test2 is ACK
Oct  5 15:17:46 deb11-2 tac_plus-ng[40576]: 10.255.64.3 password change for 'test2' from 10.20.20.19 succeeded [Password change was successful.] (profile=admins)
```
The authentication process on Juniper QFX:

<img width="751" alt="Screenshot 2022-10-05 at 21 18 28" src="https://user-images.githubusercontent.com/40116783/194098484-2e6921de-abe5-4fb8-a892-8db627058322.png">

As you can see I've only added junos-exec service:
```
#!/usr/local/sbin/tac_plus-ng

id = spawnd {
	listen = { port = 49 }
	spawn = { instances min = 1 instances max = 1 }
	background = no
}

id = tac_plus-ng {
	mavis module = external {
		# Sample Perl code to create a single SHADOWFILE line:
		# perl -e 'print "demo:".crypt("demopass", qw($1$) . "demosalt" . qw($)) . ":0:0:99999:7:::\n"
		#
		setenv SHADOWFILE = /usr/local/etc/shadow_tac
		exec = /usr/local/lib/mavis/mavis_tacplus_shadow.pl
	}

	login backend = mavis chpass

	host world {
		address = ::/0
		welcome banner = "Welcome\n\n"
		enable 15 = clear secret
		key = DataLineWB3011
	}

	profile admins {
		script {
			if (service == shell) {
				if (cmd == "") {
					set priv-lvl = 15
					permit
				}
			}
			if (service == junos-exec) {
				if (cmd == "") {
					set local-user-name = admin
					permit
				}
			}
		}
	}

	group admins

	user test2 {
		password login = mavis
		member = admins
	}

	ruleset {
		rule {
			script {
				if (member == admins) { profile = admins permit }
			}
		}
	}
}

```

**Comment by MarcJHuber** [comment]
Hi,

I'd appreciate more debug output on this issue. Could you please run the daemon with "-d -1" and retry?

Thanks,

Marc

**Comment by lst123** [comment]
Hi Mark, 
I've just tested a password changing process in case when Juniper box is configured to use Cisco ISE (we don't use it anymore, but still have):
<img width="605" alt="Screenshot 2022-10-07 at 15 35 53" src="https://user-images.githubusercontent.com/40116783/194524012-66c004d5-b06c-49f8-a257-9800c5b4c55e.png">

Maybe this could help. 
I'm going to test this process on the other vendors and return back with the results. 

Thank you.

**Comment by MarcJHuber** [comment]
Hi,

I've had another look at yesterday's debug log -- could you please check whether changing TAC_PLUS_AUTHEN_STATUS_GETPASS to TAC_PLUS_AUTHEN_STATUS_GETDATA in authen.c:do_chpass() makes a difference?

Thanks,

Marc

<pre>
diff --git a/tac_plus-ng/authen.c b/tac_plus-ng/authen.c
index edeaf2c..ae0e7a5 100644
--- a/tac_plus-ng/authen.c
+++ b/tac_plus-ng/authen.c
@@ -561,7 +561,7 @@ static void do_chpass(tac_session * session)

        msg = eval_log_format(session, session->ctx, NULL, fmt, io_now.tv_sec, NULL);

-       send_authen_reply(session, TAC_PLUS_AUTHEN_STATUS_GETPASS, msg, 0, NULL, 0, TAC_PLUS_REPLY_FLAG_NOECHO);
+       send_authen_reply(session, TAC_PLUS_AUTHEN_STATUS_GETDATA, msg, 0, NULL, 0, TAC_PLUS_REPLY_FLAG_NOECHO);
        session->user_msg = NULL;
        return;
     }
@@ -570,7 +570,7 @@ static void do_chpass(tac_session * session)
        return;
     }
     if (!session->authen_data->msg) {
-       send_authen_reply(session, TAC_PLUS_AUTHEN_STATUS_GETPASS, "Retype new password: ", 0, NULL, 0, TAC_PLUS_REPLY_FLAG_NOECHO);
+       send_authen_reply(session, TAC_PLUS_AUTHEN_STATUS_GETDATA, "Retype new password: ", 0, NULL, 0, TAC_PLUS_REPLY_FLAG_NOECHO);
        return;
     }
</pre>

**Comment by lst123** [comment]
Hi Mark again, 
I can confirm, your patch works as expected. I'm able to change the password and login with a new one:

<img width="552" alt="Screenshot 2022-10-07 at 21 55 30" src="https://user-images.githubusercontent.com/40116783/194596907-310526d2-60cb-4a98-b10c-89111bd3b00a.png">

Thank you!

**Comment by MarcJHuber** [comment]
Hi,

thanks again for testing this. I'll push a proper fix (that keeps TAC_PLUS_AUTHEN_CHPASS intact) within the next couple of minutes.

Cheers,

Marc

**Comment by MarcJHuber** [comment]
Closed. I assume yesterday's push worked fine.. Thanks a lot for testing!

**Comment by lst123** [comment]
Hi Mark, 
Thank you for your help!
Yes it works fine. 

Regards,
Yaroslav
