### ISSUE TITLE
autocmd closing immediately - Cisco IOS

### ISSUE THREAD

**Issue by jamenlang** [MarcJHuber/event-driven-servers#72]
this isn't necessarily an issue with tac_plus-ng, but I thought I'd post here in case someone has a fix. 

I'm looking for an option to set the terminal length to 0 for one specific user and not affect other users.

this seems like a really good use of autocmd.

regular commands like 'show ver' or 'show run' seem to work just fine, but if I put in 'terminal length 0' the session closes immediately after login.

If I modify the command to be an invalid command like 'length 0' , I get a message to the terminal 

Line has invalid autocommand "length 0"

so I know it's working... ish.

my configuration in tac_plus-ng is 

```
                        if (service == shell) {
                                if (cmd == "")
                                        set priv-lvl = 15
                                set autocmd = "terminal length 0"
                                permit
                        }
```

**Comment by MarcJHuber** [comment]
Hi Jamen,

yes, autocmd will terminate after execution and IOS doesn't support multiple autocmd AV pairs.

For your particular use-case, the equivalent of "stty rows 0" on the client side might be an option.

Cheers,

Marc
