### ISSUE TITLE
An error message is displayed when you run the openssl passwd -crypt clear_text_password command to create a password

### ISSUE THREAD

**Issue by lenz-li** [MarcJHuber/event-driven-servers#73]
<img width="422" alt="d839185695fd293a7135def55421f02" src="https://github.com/MarcJHuber/event-driven-servers/assets/75249916/833f1f16-5faf-4c6b-a9bc-5ac80c127914">

![image](https://github.com/MarcJHuber/event-driven-servers/assets/75249916/d1f2e3f0-ae20-4807-9d39-886e255bd36f)

**Comment by MarcJHuber** [comment]
Hi,

no, the configuration will not accept shell commands. I'll drop the legacy references to "-crypt", but I don't think I've ever said that "openssl passwd ..." in configuration files would be legit. You can use that to compute password hashes and then use those hashes in the configuration file. Everything else is out of context.

Cheers,

Marc

**Comment by lenz-li** [comment]
Okay, got it. Thank you
