### ISSUE TITLE
tac-plus-ng support google authenticator?

### ISSUE THREAD

**Issue by sgaibwi** [MarcJHuber/event-driven-servers#77]
Hi, Huber,

tac-plus-ng support google authenticator? One Time Password, if yes,can you give an expample?

Now my tac_plus-ng work well, use ldap,Because security,I want to implemet MFA authentication.

Thanks.

**Comment by MarcJHuber** [comment]
Hi,

OTP will work if the underlying service support stacking. E.g. for PAM, you could try [the Google Authenticator PAM module](https://github.com/google/google-authenticator-libpam.git) with the `forward_pass` option enabled. Similar solutions may exist for LDAP, but I didn't dig into that.

That being said: No, I'm sorry, I have no simple canned configuration for OTP support, but if your LDAP server transparently supports OTP then `tac_plus-ng` will, too. 

Cheers,

Marc
