### ISSUE TITLE
Username+Password+OTP second login fails

### ISSUE THREAD

**Issue by sgaibwi** [MarcJHuber/event-driven-servers#78]
I set up a freeipa server to authenticate with tacacs. There is no problem if the user name and password , but if change it to username +password +OTP , only the first login can be successful, and the second login fails unless the tacacs service area is restarted.

![1704703136878](https://github.com/MarcJHuber/event-driven-servers/assets/94779423/e0d7c0e8-3fee-4aeb-bfd9-76fa7e45f38c)
![1704702880020](https://github.com/MarcJHuber/event-driven-servers/assets/94779423/2f46d8f4-dda0-4b7a-8699-c147362b7ecd)
![1704702794522](https://github.com/MarcJHuber/event-driven-servers/assets/94779423/ac4f6319-e58f-4f5d-8044-e803b757db3d)

**Comment by sgaibwi** [comment]
tac_plus-ng version d9b28f5d5bf3989a1ec1c222b2a3e2f880180181/PCRE2/ARES/CURL

free IPA:4.10.2

**Comment by MarcJHuber** [comment]
Hi,

looks like a password caching issue. I'd try with `mavis_tacplus-ng_ldap.pl` which sets the `AV_A_PASSWORD_ONESHOT` attribute by default.

Alternatively,
````
mavis module = external {
    ...
    script out { set $PASSWORD_ONESHOT = "1" }
    ...
}
````

should work, too.

Cheers,

Marc

**Comment by sgaibwi** [comment]
Hi,

Your analysis is correct,I insert the script in the mavis moudel, the MFA login works perfectly now。

But there's something wrong with the accesslog. Accesslog is shown below:

2024-01-09 08:56:06 +0800       10.2.2.2     zhangsan    vty0    10.1.1.1     shell login succeeded
2024-01-09 08:56:06 +0800       10.2.2.2     zhangsan    vty1    10.1.1.1     shell login failed [Invalid credentials (463)]
2024-01-09 08:56:09 +0800       10.2.2.2     zhangsan    vty1    10.1.1.1     shell login failed [No password, did you mean noauth or anonymous ? (463)]

**Comment by MarcJHuber** [comment]
Hi,

I think these are LDAP error messages. These might be due to an anonymous LDAP bind attempt (due to LDAP_USER and/or LDAP_PASSWORD being unset).

Please try switching to mavis_tacplus-ng_ldap.pl (or ldapmavis-mt) and make sure to set LDAP_USER and LDAP_PASSWORD.  mavis_tacplus-ng_ldap.pl even checks for krbPasswordExpiration, and it seamlessly supports password changes, so it's the better choice in any way.

Cheers,

Marc

**Comment by sgaibwi** [comment]
Hi,
I restart tac_plus-ng,now it works fine! Thank your again.You can close this ticket.

**Comment by MarcJHuber** [comment]
Hi,

thanks for confirming, I'll close this issue.

Cheers,

Marc
