### ISSUE TITLE
编译中出现异常

### ISSUE THREAD

**Issue by fanbinbill** [MarcJHuber/event-driven-servers#91]
/home/xxxx/event-driven-servers/mavis/radmavis.c:107:5: warning: implicit declaration of function ‘rc_apply_config’ [-Wimplicit-function-declaration]
     rc_apply_config(rh);
     ^~~~~~~~~~~~~~~
/home/xxxx/event-driven-servers/mavis/radmavis.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-implicit-fallthrough’
gcc -o radmavis radmavis.o   -L/usr/x86_64-linux-gnu/lib -Wl,-rpath,/usr/x86_64-linux-gnu/lib -lradcli
radmavis.o: In function `main':
radmavis.c:(.text+0x26a): undefined reference to `rc_apply_config'
collect2: error: ld returned 1 exit status

**Comment by MarcJHuber** [comment]
Hi,

is your radcli installation current? rc_apply_config is available since radcli version 1.2.10 (released 2018-05-08).

Cheers,

Marc

**Comment by MarcJHuber** [comment]
Hi,

28e8b5727bdc0672e39654f0347212deecd9b4f5 likely closes this issue.

Cheers,

Marc
