### ISSUE TITLE
the error when i execute './configure tac_plus,'the following errors occurs

### ISSUE THREAD

**Issue by gouhan19980313** [MarcJHuber/event-driven-servers#92]
[root@localhost event-driven-servers-master]# systemctl status tac_plus.service
● tac_plus.service - TACACS+ Service
   Loaded: loaded (/etc/systemd/system/tac_plus.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2024-05-08 02:25:59 EDT; 14s ago
 Main PID: 33622 (tac_plus)
   CGroup: /system.slice/tac_plus.service
           ├─33622 tac_plus: 0 connections, accepting up to 600 more
           └─33624 tac_plus: 0 connections

May 08 02:25:59 localhost.localdomain systemd[1]: Started TACACS+ Service.
May 08 02:25:59 localhost.localdomain tac_plus[33622]: startup (version GIT info is unavailable. This build might be outdated. Please make sure to update to the latest GIT version...t request.)
May 08 02:25:59 localhost.localdomain tac_plus[33622]: epoll event notification mechanism is being used
May 08 02:25:59 localhost.localdomain tac_plus[33622]: bind to [::]:4949 succeeded
May 08 02:25:59 localhost.localdomain tac_plus[33624]: epoll event notification mechanism is being used
May 08 02:25:59 localhost.localdomain tac_plus[33624]: - Version GIT info is unavailable. This build might be outdated. Please make sure to update to the latest GIT version before...initialized
Hint: Some lines were ellipsized, use -l to show in full.
[root@localhost event-driven-servers-master]#

**Comment by MarcJHuber** [comment]
Hi,

this issue is pretty close to "invalid". Your copy-paste is a runtime warning from systemd and not from the configure script, and the "GIT info is unavailable" is likely due to a missing .git directory, perhaps caused by not using the standard git CLI tools.

Cheers,

Marc
