### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by fanbinbill** [MarcJHuber/event-driven-servers#93]
OS:debin10
内核版本：5.4.56.bsk.10-amd64
软件版本：tac_plus version 28e8b5727bdc0672e39654f0347212deecd9b4f5/PCRE2/CRYPTO/ARES/CURL/SSL

-----------现象

近期升级后，发现在高并发场景下，存在一些报错：

May 10 11:15:07 xxxx tac_plus[1851760]: scm_send_msg (/root/event-driven-servers/mavis/spawnd_accepted.c:217): Connection refused
May 10 11:15:07 xxxx tac_plus[1851760]: scm_send_msg: sendmsg: Connection refused
May 10 11:15:07 xxxx tac_plus[1851760]: scm_send_msg (/root/event-driven-servers/mavis/spawnd_accepted.c:217): Connection refused

从现象看，是连接被拒绝

**Comment by MarcJHuber** [comment]
Hi,

the "Connection refused" message at this place is the error code returned by sendmsg(), likely indicating that the other side of the connection is no longer running. Were there any other issues, e.g. did one of the worker processes terminate?

Cheers,

Marc

**Comment by fanbinbill** [comment]
您的意思是： 可能是交换机侧已经断开tcp连接吗，但是从日志看，我会认为是server端拒绝连接请求

**Comment by MarcJHuber** [comment]
Hi,

the listener component accepts connections and forwards them (via UNIX domain sockets) to the worker processes. Apparently, one of the worker processes was no longer able to handle the corresponding connection. I've no idea why that happend, and the best guess is that the worker process did have an issue (resource constraints, crash, whatever).

Cheers,

Marc
