### ISSUE TITLE
tac_plus compile error

### ISSUE THREAD

**Issue by routerid** [MarcJHuber/event-driven-servers#95]
Hello, I am a network engineer, chance to see this project on github. I downloaded the source code of the project and failed to compile and install it on centos7.9. The following error message appears during compilation:
![微信截图_20240609153826](https://github.com/MarcJHuber/event-driven-servers/assets/34803923/8b73691d-49df-4d90-965d-e893fd8ce6bd)

System version：
  CentOS Linux release 7.9.2009 (Core)

**Comment by MarcJHuber** [comment]
Hi,

the C-ARES coming with CentOS 7.9 seems to be outdated. You can either "./configure --without-ares" to skip DNS support or upgrade your C-ARES installation to the current version (from https://github.com/c-ares/c-ares).

Cheers,

Marc
