### ISSUE TITLE
Support for variable option LDAP sizelimit in libmavis-mt

### ISSUE THREAD

**Issue by sanjmonkey** [MarcJHuber/event-driven-servers#99]
Hey Marc,

I noticed the `sizelimit` parameter used in `ldap_search_ext_s` happens to be hard coded to 100.  Would you be open to the option of supporting this as an environment variable defaulting to 100?

Thanks!
Sandy

**Comment by MarcJHuber** [comment]
Hi Sandy,

good idea, I'll add support for a "LDAP_SIZELIIMIT" environment variable for that.

Thanks,

Marc
